apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  DB_HOST: ZGItcG9zdGdyZXM=
  POSTGRES_DB: ZGphbmdvLWRi   
  POSTGRES_PASSWORD: MTIjNUxJSUJNWEhFOFQ0  
  POSTGRES_USER: ZGphbmdv 
  DEBUG: "dHJ1ZQ=="