apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: myingress
spec:
  rules:
  - host: usmanofff.ru
    http:
      paths:
      - pathType: Prefix
        path: /test
        backend:
          service:
            name: app-cluster-ip
            port: 
              number: 3003
  
