---
stages:
  - build
  - deploy
docker_build:
  stage: build
  rules:
    - if: $CI_TAG =~ /^v\d+.\d+/
      exists:
        - Dockerfile
    - when: on_success
    - when: manual
  before_script:
     - docker login -u "$CI_REG_USER" -p "$CI_REG_PASSWORD"
  script:
    - env
    - export
    - tag=$CI_TAG
    - echo "Running build with tag $tag"
    - docker build -t usmcode/diplom:$tag .
    - docker push usmcode/diplom:$tag

app_deploy: 
  stage: deploy
  environment: production
  script:
    - env
   # - export
   # - tag=$CI_TAG
   # - echo "Deploy app django-pg-docker-tutorial build version $tag"
   # - export KUBECONFIG=/opt/.kube/config
   # - helm upgrade --atomic --timeout 600s --set app-dep.tag=$tag --install --namespace $CI_NAMESPACE --create-namespace app-dep git@gitlab.com:sfc_diplom/diplom.git-/app-v1.1.tgz 
   # #- helm upgrade --install -n diplom my-app --atomic --timeout 900s app-dpdt/
   # - kubectl get pods -n $CI_NAMESPACE