apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-django-deployment
  labels:
    k8s-app: {{.Release.Name}}-django
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Release.Name}}-django
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-django # Service will look for those PODS labels 
        gitlab: diplom
        owner: DenisUsmanov
    spec:
      containers:
      - name: {{.Release.Name}}-django
        image: "{{.Values.djangoContainer.image}}:{{.Values.app.tag | default .Chart.AppVersion }}"
        command: {{.Values.djangoContainer.command}}
        args: ['-c', 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3003']
        ports:
          - containerPort: {{.Values.djangoContainer.ports}}
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_PASS
            
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DEBUG

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key:  POSTGRES_PASSWORD



