apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  DB_HOST: {{.Values.data.DB_HOST}}
  POSTGRES_DB: {{.Values.data.POSTGRES_DB}}   
  POSTGRES_PASSWORD: {{.Values.data.POSTGRES_PASSWORD}}  
  POSTGRES_USER: {{.Values.data.POSTGRES_USER}}
  DEBUG: {{.Values.data.DEBUG}}