apiVersion: v1
kind: Service
metadata:
  name: app-cluster-ip # this is the name of the service that will be available to the application
  labels:
    env: app-cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.djangoContainer.ports}}
  selector:
    app: {{.Release.Name}}-django